### ISSUE TITLE
Show sample configuration in README

### ISSUE THREAD

**Issue by Compro-Prasad** [Boruch-Baum/emacs-keypress-multi-event#1]

**Comment by Boruch-Baum** [comment]
Hi. The readme does include links to a sample, the [home-end](https://github.com/Boruch-Baum/emacs-home-end) package for which this was originally written. I'm hoping that the volunteers over at [MELPA](https://github.com/melpa/melpa/pull/5595) will soon merge that PR so that the complete set (this package and [home-end](https://github.com/Boruch-Baum/emacs-home-end)) can be available together on MELPA. In fact, originally, I had the two integrated as a single package, but that violated MELPA's contribution standards, so I had to split the two, and here we are in the 'transition' period waiting for the second action to happen.

**Comment by Compro-Prasad** [comment]
What if someone just copy paste a `use-package` code snippet to just try out this package. I believe many of regular Emacs users wont even get what you are talking about. You need a proper screenshot for the purpose. Just want to mention that it looks more appealing to include prewritten config and screenshots showing what this package does.
